### ISSUE TITLE
Redis protocol: parsed unsupported command 'PING'

### ISSUE THREAD

**Issue by chakrikodali** [twitter/twemproxy#113]
```
[Tue May 21 02:00:03 2013] nc_redis.c:923 parsed unsupported command 'PING'
[Tue May 21 02:00:03 2013] nc_core.c:207 close c 8 '192.168.33.1:52511' on event 0001 eof 0 done 0 rb 14 sb 0: Invalid argument
```

Is there a specific reason why ping is not supported by nutcracker? 
Will it be ever supported?

Popular java redis client (jedis) triggers a PING first before allocation a connection from JEDISPOOL? Are there any work arounds? (apart from hacking the jedis source)

**Comment by BridgeAR** [comment]
Closing the connection on a not supported command is not a good way to handle such errors in my opinion. I do not have any insight in twemproxy but Redis constantly adds new commands and I guess they are not supported out of the box especially as they might not all work with twemproxy. So instead of just closing the connection in such cases wouldn't it be a much better solution to return the same error as Redis in case of not supported commands (`ERR unknown command 'info'`)?

Removing commands from a client is not the proper solution in such a case. Many people might run into issues by trying to fire a unsupported command and without looking at the supported commands it's difficult to find out what the reason for the behavior is.

As node_redis maintainer I'm about to remove options that don't have substantial benefit. Not using the info command is one of those options. Otherwise clients are just bloated with options that have to be maintained and make things more complicated than they have to be. Handling a unknown command on the other hand is simple and can be handled without any option.

Changing the behavior from closing the connection to returning an error instead is likely not even a real breaking change as it is highly unlikely that people rely on a forced connection abort in real code.

To conclude: it would be great if you'd be open for such a change. I think quite a few people would benefit from it and it makes live easier for client maintainers.

Reference: https://github.com/NodeRedis/node_redis/issues/704
Ping @manjuraj

**Comment by xwiz** [comment]
Supported. It's better to issue a warning for unsupported commands than killing the connection. These are valid commands that Redis itself supports, so I don't exactly see the need or fairness for a proxy that supports Redis to abort connection when a valid Redis command that it doesn't support is supplied.
