### ISSUE TITLE
Can twemproxy a solution for stale data handling when using consistent hashing

### ISSUE THREAD

**Issue by ryanc4** [twitter/twemproxy#134]
Hi,

I am new to twemproxy but we have extensively using memcached in the past.

One of the problem that force us not using memcached with consistent hashing is the network partitioning problem:

a. we have a lot of memcached clients and servers
b. if a particular client failed to connect to one server (say. OldM), consistent hashing will map into another server (NewM), new data will write to the NewM from the client
c. if other servers are able to connect to the OldM, so now clients have different hashing.
d. Stale data then will occur

I am thinking if using twemproxy in a ACTIVE-PASSIVE would solve the issue for me. Anyone mind to share your experience.?

**Comment by TysonAndre** [comment]
The "failover" patch planned in https://github.com/twitter/twemproxy/issues/608 may help with that - instead of failing over to a host within the pool (auto_eject_hosts: true), fail over to a host in a different pool.

Then automatically clear the failover pool when the failover pool stops getting traffic, to avoid storing the data after all hosts in the main pool recover

> I am thinking if using twemproxy in a ACTIVE-PASSIVE would solve the issue for me. Anyone mind to share your experience.?

I'm not certain what this means
