### ISSUE TITLE
maximum number of server_connections

### ISSUE THREAD

**Issue by sachinpkale** [twitter/twemproxy#250]
We have following setup of twemproxy on production:
    5 service instances 
    1 twemproxy instance
    4 redis instances
Service instances are connected to twemproxy with max_active_connections = 1000.
Currently, we are having server_connections: 1000 in the twemproxy configuration. But, as we are having 5 service instances each with max 1000 connections, should we increase the server_connections value to 5000?

**Comment by xinyu7git** [comment]
@idning what 's meaning of "server_connections" for memcached? Twemproxy is also single thread.

**Comment by charsyam** [comment]
@xinyu7git 

twemproxy is single thread. but server_connections are meaningful for memcached.
because memcached is multi threaded for read(in different slab)

so.

1. client A request large data set for memcached A
2. client B request large data set for memcached A

in  server_connections == 1, client B should wait for finishing Task A.
but server_connections > 1, client B can work with memcached A

**Comment by manjuraj** [comment]
nobody reads docs - https://github.com/twitter/twemproxy/blob/master/notes/recommendation.md#server_connections--1
