### ISSUE TITLE
Get incomplete data when run lua script with eval

### ISSUE THREAD

**Issue by tobegit3hub** [twitter/twemproxy#319]
Recently we have deployed twemproxy and found some problems when we try to `eval` our script. We're using PHP and write lua script to get data from redis. The script looks like this.

```
$script = 'local ret = {}
local ct = table.getn(KEYS)
for i=1, ct do
	ret[i] = cjson.encode(redis.call("hgetall",KEYS[i]))
end
return ret
';
```

We pass the keys then get the values of these keys by one time. But the data is incomplete.

It's wired that the response data is quite different when we change the sequence of the array to input. Therefore we think the twemproxy will only search part of my data in only one redis cluster and return incomplete data for us.

Twemproxy doesn't support `eval` well and the problem occurs when I try to use it.

**Comment by charsyam** [comment]
@tobegit3hub I have a question?
How many redis server do you use with twemproxy?
and How many keys do you pass to lua script?
and What mean is "incomplete"?
Do you mean protocol is not correct?(disconnect from twemproxy?)
or Some key is missing?

If it is second one, It can, because Keys are distributed multiple server.
so lua script can't get all data with hgetall.

see reference. https://github.com/twitter/twemproxy/blob/master/notes/redis.md

**Comment by tobegit3hub** [comment]
It's the second one and we pass some keys which are not in the same server. Thanks @charsyam and we didn't read the document well. You can close this because it's well documented. But any chance to support it?

**Comment by charsyam** [comment]
@tobegit3hub I think it is hard to support, because lua script eval in redis server.
and redis server can't know it is distributed.

**Comment by tobegit3hub** [comment]
You're right and thanks for your replying :smiley:
