### ISSUE TITLE
twemproxy for the cloud!

### ISSUE THREAD

**Issue by pauldavidgilligan-msm** [twitter/twemproxy#355]
Hi, I can see a lot of PR's and many keen developers on this project and I am wondering what final code would be useful for cloud based deployments? For our cloud systems DNS entries evolve over time and so a twemproxy members list might not be complete during twemproxy startup which leads to:

```
[2015-04-28 15:12:15.824] nc_conf.c:116 init conf server 0x6bc5f0
[2015-04-28 15:12:15.844] nc_util.c:495 address resolution of node 'n3.xx-redis1.xx.xxx.internal' service '6379' failed: Name or service not known
[2015-04-28 15:12:15.844] nc_util.c:274 free(0x6bcbc0) @ nc_string.c:54
[2015-04-28 15:12:15.844] nc_conf.c:499 conf: directive "servers" has an invalid value
[2015-04-28 15:12:15.844] nc_conf.c:466 pop 'n3.xx-redis1.xx.xxxx.internal:6379:1 redis3'

```
I have seen the idea of re-configurable YAML which is excellent and might help out in this situation. What we are looking for is a patch that we can use to ensure twemproxy always starts up even with backend network issues and then heals itself when the redis nodes in this case are registered on the network.

The other option would be to find "one" live redis start twemproxy and then later in the provisioning re-configure.

Any thoughts would be so welcome.

**Comment by therealbill** [comment]
First, I am in favor of the notion of Twemproxy starting up even if it can't yet connect to the backend nodes. It should, of course, not accept commands until it has them, but it should at least start up.

That said, if you want to use DNS you'll need to ensure you use very short TTLs and that the client-side isn't doing any caching.

Regarding a reconfigurable YAML, I'd love to see a configuration API as Redis has (though not necessarily the same format - just using it as an example) such that you could start Twemproxy with no configuration and "program" it once active. This is an excellent and very useful feature for cloud based deployments because it allows you to deploy a bank of system and add/alter at runtime. As containers penetrate deeper into our stacks this will become even more useful.

Note this last concept of a blank-slate startup would also meet the criteria of being able to start Twemproxy w/o the backends available yet because it would require Twemproxy to start up successfully and wait for backends to talk to.

I'm not sure if I've submitted an issue for that feature request yet. Perhaps I can write it up in more detail today.

**Comment by pauldavidgilligan-msm** [comment]
that is excellent thank you, if we could speed through something beers all round ! I am not keen on writing "work-a-rounds" making the start more robust is the way to go!

:+1:

**Comment by moneynerffy** [comment]
Hey this is a great idea, we would love to see this on our project.

**Comment by manjuraj** [comment]
The future is here and it containerized on the cloud. This patch https://github.com/twitter/twemproxy/commit/fd34c29bb69861b37eea786bd84a7e437ab8bb7c enables address resolution of backend servers to be lazy. This means that the resolution of DNS names happens on connection requests to the server rather than on startup... Who is buying beers? :)

Would you appreciate if you'll could test this patch and confirm that it works as expected. Happy Friday!

**Comment by charsyam** [comment]
@manjuraj Yes. this is simple than mine :)

**Comment by manjuraj** [comment]
thanks for the effort @charsyam

**Comment by tom-dalton-fanduel** [comment]
Tested this today with a simple Elasticache replication group of 1 master and 2 slaves. Manually promoting a slave to the new master (in the AWS console) results in write failures for around 15 secs, before the primary fqdn begins to resolve against the new master, whereupon writes start working again. Most excellent :-)

**Comment by manjuraj** [comment]
Excellent. Thanks a lot @tom-dalton-fanduel. This is very helpful

**Comment by pauldavidgilligan-msm** [comment]
well done guys !! of cause I can supply the beers there is life in twemproxy yet !
