### ISSUE TITLE
Did tcpkeepalive make it into the current codebase?

### ISSUE THREAD

**Issue by jennyfountain** [twitter/twemproxy#482]
I am see a couple references to it in issues and thought I saw a merge but do not see documentation.

Thanks

**Comment by manjuraj** [comment]
https://github.com/twitter/twemproxy/blob/74af2fb2d5d3e214d8c0741a4b0ebb7d93572fc8/src/nc_proxy.c#L361-L365

**Comment by manjuraj** [comment]
https://github.com/twitter/twemproxy/search?utf8=%E2%9C%93&q=tcpkeepalive

**Comment by jennyfountain** [comment]
@manjuraj Perfect I thought so after reviewing myself but I don't' trust my eyes sometimes :D  

This the doc information?

tcpkeepalive: A boolean value that controls if tcp keepalive enabled. Defaults to false.
tcpkeepidle: The time value in msec that a connection is in idle, and then twemproxy check this connection whether dead or not.
tcpkeepcnt: The number of tcpkeepalive attempt check if one idle connection dead times when the client always had no reply.
tcpkeepintvl: The time value in msec that the interval between every tcpkeepalive check when the client always had no reply.

**Comment by TysonAndre** [comment]
The work on redis sentinel also includes lowering the tcpkeepalive timeout in `support set keepalive interval parameter` in https://github.com/twitter/twemproxy/pull/324  , so more updates to keepalive behavior will probably be in an upcoming twitter/twemproxy 0.6.0 release

https://github.com/twitter/twemproxy/issues/608 is merging in changes from https://github.com/ifwe/twemproxy , which included 324 and patches to 324.

Closing this because `Did tcpkeepalive make it into the current codebase?` was answered
