### ISSUE TITLE
Support for BRPOP and BLPOP

### ISSUE THREAD

**Issue by mcanonic** [twitter/twemproxy#519]
Hi,
I saw the notes/redis.md file and I'm wondering if the unsupported commands are somethin that you are working on it or not. Just to know if the (near?) future these commads like BRPOP e BLPOP will be supported.
Thanks
M

**Comment by MichaelScofield** [comment]
any update?

**Comment by TysonAndre** [comment]
It's very likely the decision to leave it out was deliberate on the part of the original maintainers - it was documented that the command is not supported.

If twemproxy has 200 clients and a small number of redis servers, and one of them issues a `BRPOP` or `BLPOP`, then 199 other clients will see an unexpected pause of an unknown length (for commands forwarded to the same server), possibly even seconds, causing an unexpected delay and adversely impacting the overall host/application performance, in a reason that those 199 clients have no visibility into.

- Currently, I believe twemproxy only supports a single server connection, even if the configuration allows more than one connection to a backend server.
- This would manifest as random pauses and would make twemproxy appear to be extremely unreliable
- Application authors would need to know what twemproxy's timeouts were, in order to make sure that a lower timeout was passed to BLPOP, etc.

As a workaround, it's already possible to call BLPOP/BRPOP in lua scripting (eval) if you're sure that your use case has timeouts properly configured or won't have adverse performance impact from blocking commands interfering with non-blocking commands.

- In theory, separate server connections could be allocated for use exclusively with blocking commands, but that goes against the current design, and is difficult to implement correctly in C
