### ISSUE TITLE
Is it still maintained?

### ISSUE THREAD

**Issue by idirouhab** [twitter/twemproxy#560]
I see that the last commit was more than one year ago and there's a bunch of PR opened. Is it still maintained?

Thanks!

**Comment by silviucpp** [comment]
I doubt ..

**Comment by tuananh** [comment]
dynomite looks like a better maintain project https://github.com/Netflix/dynomite/commits/dev

**Comment by xginn8** [comment]
I've merged some PRs from this project into my fork, https://github.com/xginn8/twemproxy. Feel free to open PRs and issues there.

**Comment by h0tw1r3** [comment]
twmemcache development continued as part of [pelikan](https://github.com/twitter/pelikan)

**Comment by TysonAndre** [comment]
> twmemcache development continued as part of pelikan

That's unrelated and would be a comment for https://github.com/twitter/twemcache/issues

https://github.com/twitter/twemcache is a separate project with 3 cache servers, none of which are proxies
("Twemcache (pronounced "tw-em-cache") is the Twitter Memcached. Twemcache is based on a fork of Memcached v.1.4.4 that has been heavily modified to make to suitable for the large scale production environment at Twitter.")

> Currently Pelikan yields three main products, all of which are backends/servers.
> 1. pelikan_twemcache: a Twemcache replacement
> 2. pelikan_slimcache: a Memcached-like server with ultra-low memory overhead- compared to Memcached/Redis, the per-key overhead is reduced by up to 90%
> 3. pelikan_pingserver: an over-engineered, production-ready ping server useful as a tutorial and for measuring baseline RPC performance

**Comment by TysonAndre** [comment]
I've merged some of the bug fixes or new features I or others have proposed recently (such as https://github.com/twitter/twemproxy/pull/595) (or years ago, such as https://github.com/twitter/twemproxy/pull/545 or ) into the fork https://github.com/ifwe/twemproxy 
(I'm the only developer currently working on that fork, and only infrequently)

- https://github.com/ifwe/twemproxy/ builds `nutcracker` which is intended for use only with memcached clients. It adds some features such as a `failover` pool
- https://github.com/ifwe/twemproxy/tree/build-nutredis builds `nutredis` which is intended for use only with redis clients. This adds andyqzb's redis-sentinel patches. (The interactions between the patches are untested which is why there are currently two branches)

**Comment by TysonAndre** [comment]
I was added as a collaborator yesterday, see https://github.com/twitter/twemproxy/issues/608 - new releases are planned
